name: ECR image
description: Builds and pushes AWS ECR image
inputs:
  aws-role-to-assume:
    description: 'AWS role to assume. Use either role or access key, not both.'
    required: false
  aws-access-key-id:
    description: 'AWS access key'
    required: false
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: false
  aws-region:
    description: 'AWS region'
    required: true
  ecr-repo:
    description: 'ECR repo name'
    required: true
  ecr-tag:
    description: 'ECR tag'
    required: true
  docker-build-args:
    description: 'Args passed to docker build'
    required: false
    default: '-f ./Dockerfile .'
outputs:
  ecr-image:
    description: 'Full address of the ECR image'
    value: ${{ steps.build-push.outputs.ecr-image }}

runs:
  using: "composite"
  steps:
  - name: Assume AWS role
    if: ${{ inputs.aws-role-to-assume }}
    uses: aws-actions/configure-aws-credentials@v1.6.0
    with:
      role-to-assume: ${{ inputs.aws-role-to-assume }}
      aws-region: ${{ inputs.aws-region }}
  - name: Configure AWS credentials
    if: ${{ !inputs.aws-role-to-assume }}
    uses: aws-actions/configure-aws-credentials@v1.6.0
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: ${{ inputs.aws-region }}
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1
  - name: Build, tag, and push image to Amazon ECR
    id: build-push
    shell: bash
    env:
      ECR_IMAGE: "${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repo }}:${{ inputs.ecr-tag }}"
    run: |
      docker build -t $ECR_IMAGE ${{ inputs.docker-build-args }}
      docker push $ECR_IMAGE
      echo "::set-output name=ecr-image::$(echo $ECR_IMAGE)"
